### ISSUE TITLE
build.rs not working

### ISSUE THREAD

**Issue by larseggert** [libpnet/netmap_sys#1]
I'm trying to build this on my local Linux box, and the stuff in `build.rs` seems to be failing.

First, I think I needed to install `clang`, which wasn't super-obvious. But even with that done, I still hit this error:

```
[lars@tux: ~/rustcore] cargo build -v
   Compiling rust-netmap v0.0.4 (https://github.com/libpnet/rust-netmap.git#ab947ee2)
     Running `rustc /tmp/git/checkouts/rust-netmap-2baeba280d3ef56f/master/src/lib.rs --crate-name rust-netmap --crate-type rlib --crate-type dylib -C prefer-dynamic -g --cfg feature="default" --cfg feature="netmap_with_libs" -C metadata=10a85511dfe14665 -C extra-filename=-10a85511dfe14665 --out-dir /mnt/home/vmhome/rustcore/target/deps --emit=dep-info,link -L dependency=/mnt/home/vmhome/rustcore/target/deps -L dependency=/mnt/home/vmhome/rustcore/target/deps -Awarnings -L native=/mnt/home/vmhome/rustcore/target/build/rust-netmap-10a85511dfe14665/out -l static=rust_netmap_user`
error: could not find native static library `rust_netmap_user`, perhaps an -L flag is missing?
Could not compile `rust-netmap`.

Caused by:
  Process didn't exit successfully: `rustc /tmp/git/checkouts/rust-netmap-2baeba280d3ef56f/master/src/lib.rs --crate-name rust-netmap --crate-type rlib --crate-type dylib -C prefer-dynamic -g --cfg feature="default" --cfg feature="netmap_with_libs" -C metadata=10a85511dfe14665 -C extra-filename=-10a85511dfe14665 --out-dir /mnt/home/vmhome/rustcore/target/deps --emit=dep-info,link -L dependency=/mnt/home/vmhome/rustcore/target/deps -L dependency=/mnt/home/vmhome/rustcore/target/deps -Awarnings -L native=/mnt/home/vmhome/rustcore/target/build/rust-netmap-10a85511dfe14665/out -l static=rust_netmap_user` (exit code: 101)
```

Looking at `build.rs`, I noticed that `/usr/include/net/netmap_user.h` does not exist on my netmap-enabled system, but even after making this a symlink to my `netmap_user.h`, I see this failure.

**Comment by mrmonday** [comment]
Could you tell me a bit more about your setup? Which distro are you using? How did you install netmap? After running `cargo build`, what is the output of `ls target/build/rust-netmap-*/out`? You don't actually need clang, the but the build script doesn't detect available compilers currently, perhaps I should add a note in the README. I've just built it locally and it seems fine, so I guess there's something different about your setup which is stopping it working.

**Comment by mrmonday** [comment]
Could you also post the output of:

```
clang -DNETMAP_WITH_LIBS =Dstatic= -Dinline= -x c -fPIC -O2 -c /usr/include/net/netmap_user.h -o $(mktemp)
```

Please?

**Comment by larseggert** [comment]
Thanks for looking into this. I run Debian in a local VM on my Mac:

```
[lars@tux: ~] lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.0 (jessie)
Release:    8.0
Codename:   jessie
```

I'm running the `next` branch of Luigi's public netmap repo at https://code.google.com/p/netmap/. Build and installed via `make` and `sudo make install`, plus adding `netmap` to `/etc/modules` and adding some udev rules so non-root can use `/dev/netmap`.

After `cargo build`, the directory is empty:

```
[lars@tux: ~/rustcore] cargo build
    Updating git repository `https://github.com/libpnet/rust-netmap.git`
   Compiling rust-netmap v0.0.4 (https://github.com/libpnet/rust-netmap.git#ab947ee2)
error: could not find native static library `rust_netmap_user`, perhaps an -L flag is missing?
Could not compile `rust-netmap`.

To learn more, run the command again with --verbose.
[lars@tux: ~/rustcore] ls target/build/rust-netmap-*/out
[lars@tux: ~/rustcore]
```

As for the `clang` command (I guess you meant `-Dstatic=` and not `=Dstatic=`):

```
[lars@tux: ~/rustcore] clang -DNETMAP_WITH_LIBS -Dstatic= -Dinline= -x c -fPIC -O2 -c /usr/include/net/netmap_user.h -o $(mktemp)
/usr/include/net/netmap_user.h:77:10: fatal error: 'net/netmap.h' file not found
#include <net/netmap.h>
         ^
1 error generated.
```

It looks like `make install` in netmap doesn't install the header files. Hm. Let me go digging.

**Comment by mrmonday** [comment]
I did, I knew something looked weird about that line... I suppose I should have run it myself and found out. It looks like if the header files are in place things should hopefully start working for you - good luck!

**Comment by larseggert** [comment]
Yep, with the headers manually symlinked into place, it builds - thanks!

**Comment by mrmonday** [comment]
Great, glad you got it working!
